---
version: "2"
linters:
  enable:
    - scopeguard
  settings:
    custom:
      scopeguard:
        type: module
        description: "scopeguard identifies variables with unnecessarily wide scope and suggests moving them to tighter scopes."
        original-url: "https://fillmore-labs.com/scopeguard"
        settings:
          max-lines: 10
