name: CI

on:
  workflow_call:
  push:
    branches:
      - "feature/*"
      - "feat/*"
      - "fix/*"
      - "bugfix/*"
      - "hotfix/*"
      - "refact/*"
      - "refactor/*"

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        id: golang-with-cache
        with:
          go-version-file: go.mod

      - name: Running scopeguard
        run: |
          go install fillmore-labs.com/scopeguard@latest
          scopeguard ./...

      - name: Running lint
        uses: golangci/golangci-lint-action@v8
        timeout-minutes: 5
        with:
          version: v2.4
          skip-cache: false

      - name: Test
        run: |
          ENV=test go test . -cover

      - name: Docker Examples
        working-directory: example/full
        run: |
          docker compose up -d
          sleep 10

      - name: Test Examples
        working-directory: example/full
        run: |
          ENV=test go test ./... -cover

      - name: Save Golang cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.golang-with-cache.outputs.build-cache-path }}
            ${{ steps.golang-with-cache.outputs.module-cache-path }}
          key: ${{ steps.golang-with-cache.outputs.cache-key }}
